name: Update sub-web

on:
  workflow_dispatch:
  push:
    paths:
    - 'subconverter/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.2

    # Runs a set of commands using the runners shell
    - name: Update sub-web
      run: |
        rm -rf sub-web
        git clone https://github.com/zhongfly/sub-web.git
        sudo rm -rf sub-web/.git
    - name: Check subconverter
      run: |
        sudo chmod +x subconverter/subconverter.exe
        sed -i 's/api_mode=false/api_mode=true/g' subconverter/pref.ini
    - uses: autosuite/autocommit@master
      with:
        commit-message: 'Update sub-web from zhongfly/sub-web'
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        branch: master
